######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 17:12:28 2013
######################################################################

QT += core
CONFIG += console
TEMPLATE =  app
TARGET = 
DEPENDPATH += . \
              ../../include/ \
              ../../plugins/qt 

INCLUDEPATH += . \
               ../../include/  \
               ../../plugins/qt 

# Input
HEADERS += test.h \
           test2.h \ 
    gccollectcheck.h

SOURCES += main.cpp \
    bindings.cpp \
    context.cpp \
    interop.cpp \
    values.cpp \
    gccollectcheck.cpp \
    test.cpp \
    test2.cpp
           

DESTDIR = ../../bin/

unix {
    DEFINES += "UNIX=1"
    DEFINES += "LINUX=1"
    DEFINES += "GCC=1"
}

win32 {
    DEFINES += "WIN32=1"
    DEFINES +=  "MINGW=1"
}

CONFIG(debug, debug|release) {
    LIBS += -L../../lib/ -ldukqt-debug -ldukpp-03-debug
    TARGET = dukqt-tests-debug
}

CONFIG(release, debug|release) {
    LIBS += -L../../lib/ -ldukqt-release -ldukpp-03-release 
    TARGET = dukqt-tests-release
}

QMAKE_CXXFLAGS += -Wno-reorder -Wno-unused -Wno-sign-compare -w

DISTFILES +=
